import { Playfair_Display_SC, Poppins } from "next/font/google";
import "./globals.css";

const playFairDisplaySC = Playfair_Display_SC({
  weight: '400',
  variable: '--font-pfdsc',
  subsets: ['latin']
})

const poppins = Poppins({
  weight: '400',
  variable: '--font-poppins',
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${playFairDisplaySC.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
